name: Tests

on:
  pull_request:
  push:
    branches:
      - master
      - release/*

jobs:
  mocha:
    runs-on: ${{ matrix.os }}
    name: Node.js ${{ matrix.node }} on ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        node:
          - "10"
          - "12"
          - "14"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: "Install Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: "${{ matrix.node }}"

      - name: "Install dependencies"
        run: npm ci

      - name: "Run tests"
        run: npm t
